# Default settings assumes that login/password for development db are postgres/postgres
# You can change default behaviour by setting environment variables: NW_DB_USER and NW_DB_PASS
# In linux you can do this by adding following lines to .profile file in your home folder:
# export NW_DB_USER="postgres"
# export NW_DB_PASS="postgres"
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  host: localhost
  username: <%= ENV['CP_DB_USER'] || 'postgres' %>
  password: <%= ENV['CP_DB_PASS'] || 'postgres' %>


development:
  <<: *default
  database: coupons_development

test:
  <<: *default
  database: coupons_test

production:
  <<: *default